[project]
name = "llm-concepts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asttokens>=3.0.0",
    "comm>=0.2.3",
    "numpy>=2.3.3",
    "tiktoken>=0.11.0",
    "torch>=2.8.0",
]
